# Python image for the heartbeat publisher only
FROM python:3.10-slim

WORKDIR /app

# Install system dependencies
COPY publisher/heartbeat_publisher.py /app/
COPY publisher/heartbeat.xsd /app/
COPY requirements.txt /app/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Start the heartbeat script
CMD ["python", "heartbeat_publisher.py"]